Added support for converting large models
onnx/tensorflow-onnx pull request #1090
Opened 2020-09-02 19:05 UTC by TomWildenhain-Microsoft

2020-09-02 21:19 UTC, guschmue requested changes

2020-09-02 21:19 UTC, guschmue commented on tf2onnx/tf_loader.py
> +def from_function(func, input_names, output_names, large_model):
maybe use large_model=None since one might call this from some random python code

2020-09-02 21:20 UTC, guschmue commented on tf2onnx/tf_loader.py
> +def from_function(func, input_names, output_names, large_model):
other than that super lgtm.

2020-09-03 18:39 UTC, guschmue approved these changes

2020-09-03 18:40 UTC, merged

2020-10-13 16:45 UTC, OpUs-Nebula commented
Are there any plans for this support to be added to TF 1.X aswell?

2020-10-13 18:09 UTC, TomWildenhain-Microsoft commented
I believe converting saved models for TF 1.X should already support large models though I haven't tested it.  Do you have a specific model you would like to convert?  If so, please open a GitHub issue.

2020-10-14 17:52 UTC, OpUs-Nebula commented
I've tried but i get the error: "ValueError: You passed in an iterable attribute but I cannot figure out its applicable type". It's odd because it seems to compile fine until i get the protobuf size error when i don't pass --saved_model. I do have a specific model in mind. I'm fairly new to ML, so i suppose it could be user error aswell.

2020-10-14 18:12 UTC, OpUs-Nebula commented
Just added it

2021-05-25 17:44 UTC, dgoldenberg-audiomack commented
If this is fixed, why am I seeing it? see https://github.com/tensorflow/recommenders/issues/274#issuecomment-848071286

2021-05-25 17:51 UTC, TomWildenhain-Microsoft commented
Hi @dgoldenberg-audiomack, are you trying to convert your model from tensorflow to onnx?  This repo is the tf2onnx repo.  Our fix is a workaround/hack that lets us convert large TF models.  It isn't a fix to tensorflow itself.