Added conversion for WordpieceTokenizer
onnx/tensorflow-onnx pull request #1402
Opened 2021-03-17 11:21 UTC by xadupre

Signed-off-by: xavier dupré <xavier.dupre@gmail.com>

2021-03-18 02:59 UTC, TomWildenhain-Microsoft requested changes
A few comments, otherwise looks good!

2021-03-18 02:59 UTC, TomWildenhain-Microsoft commented on tf2onnx/graph.py
> +    def remove_output(self, output_name):
Looks like this is never used.

2021-03-18 02:59 UTC, TomWildenhain-Microsoft commented on tf2onnx/custom_opsets/string_ops.py
> +        json.dump(mapping, st, separators=(',', ':'))
I think you can use `json.dumps` instead if you want a string.

2021-03-25 11:33 UTC, xadupre commented on tf2onnx/graph.py
> +    def remove_output(self, output_name):
removed

2021-03-25 19:24 UTC, TomWildenhain-Microsoft approved these changes

2021-03-31 14:16 UTC, guschmue commented
@xadupre , what this merged ?

2021-03-31 17:00 UTC, merged