Added support for int64 -> string CategoryMapper.
onnx/tensorflow-onnx pull request #1660
Opened 2021-08-10 14:39 UTC by rmarrugat

2021-08-10 14:39 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/onnx/tensorflow-onnx?pullRequest=1660) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/onnx/tensorflow-onnx?pullRequest=1660) before we can accept your contribution.<br/><hr/>**rmarrugat** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/onnx/tensorflow-onnx?pullRequest=1660) it.</sub>

2021-08-10 18:02 UTC, TomWildenhain-Microsoft requested changes
Thanks for the contribution!  Please implement the constant folding case (see comment) and add two tests (constant and non constant cases).  You can copy the cases near here: https://github.com/onnx/tensorflow-onnx/blob/becdcba538338741a93129574c64a33e7e18c8a9/tests/test_backend.py#L4970

2021-08-11 08:45 UTC, xadupre commented on tf2onnx/custom_opsets/onnx_ml.py
> +        utils.make_sure((dtype == TensorProto.INT64 and in_dtype == TensorProto.STRING or \
You don't need the `\` at the end since it is inside parenthesis.

2022-03-29 03:18 UTC, hwangdeyu commented on tf2onnx/custom_opsets/onnx_ml.py
> +        if in_dtype == TensorProto.STRING:
Hi @rmarrugat , Thanks for your contribution.
This PR is been over half of a year. Would you mind create a new PR and add the unit test for it?

2023-06-05 11:34 UTC, fatcat-z commented
Close this since the latest one has been merged.

2023-06-05 11:34 UTC, closed without merging