Add load_op_libraries parameter in docs
onnx/tensorflow-onnx pull request #1853
Opened 2022-02-16 11:49 UTC by hwangdeyu

Add `--load_op_libraries` parameter in docs

Signed-off-by: hwangdeyu <dejack953@outlook.com>

2022-02-17 06:40 UTC, hwangdeyu commented on README.md
> +Some ops are not covered by the existing TensorFlow library. You can create a custom library following [Create an op](https://www.tensorflow.org/guide/create_op). Then use this parameter to load the
@garymm do you have any comment for this paremeter‘s description？

2022-02-17 17:56 UTC, guschmue requested changes

2022-02-18 03:49 UTC, hwangdeyu commented on README.md
> +    [--load_op_libraries custom_library_path]
Make sense, more different from `--custom-ops`.

2022-02-18 03:49 UTC, hwangdeyu commented on README.md
> +Some ops are not covered by the existing TensorFlow library. You can create a custom library following [Create an op](https://www.tensorflow.org/guide/create_op). Then use this parameter to load the
Done, thanks!

2022-02-21 02:46 UTC, hwangdeyu commented on README.md
> +Some ops are not covered by the existing TensorFlow library. You can create a custom library following [Create an op](https://www.tensorflow.org/guide/create_op). Then use this parameter to load the
@guschmue Please let me know if you have any more comments.

2022-03-01 03:44 UTC, hwangdeyu commented on README.md
> +Some ops are not covered by the existing TensorFlow library. You can create a custom library following [Create an op](https://www.tensorflow.org/guide/create_op). Then use this parameter to load the
Hi @guschmue , please approve it if the latest description is good. Thanks!

2022-03-01 06:01 UTC, guschmue approved these changes

2022-03-01 08:01 UTC, merged